### ISSUE TITLE
Enhancement suggestion video embed with audio

### ISSUE THREAD

**Issue by uesu** [TopiSenpai/Reddit-Discord-Bot#10]
Add video proper embed with audio, example:

I don't know if it's possible but if it's possible, It would be great

`[E0S1 Boothill - E6 HMC - E0 Ruan Mei - E1 Bronya 0 Cycle Sam (not relatable stats)](https://vxreddit.com/r/HonkaiStarRail_leaks/comments/1bvl1m0/e0s1_boothill_e6_hmc_e0_ruan_mei_e1_bronya_0/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button)`

![2024-04-04 19_51_15-#hsr-spoilers _ jieun's publishing house - Discord](https://github.com/topi314/Reddit-Discord-Bot/assets/39020293/844684e7-791d-49e6-949e-dcadeabc5aa1)

![2024-04-01 14_42_36-Window](https://github.com/topi314/Reddit-Discord-Bot/assets/39020293/a93da491-79cb-4740-aa6a-426ce25c78c2)
![2024-04-01 14_42_58-Window](https://github.com/topi314/Reddit-Discord-Bot/assets/39020293/519a867a-9e18-48e4-af60-dafdc4098de8)

A post was sent on my discord server and it has a video on it but, it doesn't show the video embed

Also this, photo/picture does not sometimes show the image embed? not sure

> Has image on first, second none

![2024-04-01 14_57_15-Window](https://github.com/topi314/Reddit-Discord-Bot/assets/39020293/88301ce4-9361-4bb7-b26c-5fc66a630da2)

> Deleted and was updated so new post (has the embed image)

![2024-04-01 14_57_04-Window](https://github.com/topi314/Reddit-Discord-Bot/assets/39020293/039fa133-39c9-4a51-a420-6dc56c9375ae)

> Updated and new post but no embed shown on discord

![2024-04-01 14_57_10-Window](https://github.com/topi314/Reddit-Discord-Bot/assets/39020293/201b986e-bebb-49d2-946d-25bbaac13a1b)

https://github.com/dylanpdx/vxReddit

https://github.com/MinnDevelopment/fxreddit

**Comment by uesu** [comment]
Also is it possible or a feature suggestion to set the profile picture and name?

**Comment by topi314** [comment]
> Also is it possible or a feature suggestion to set the profile picture and name?

this is already possible if you go into the `channel settings` > `integrations` > `webhooks`
there you can set a custom name & avatar

**Comment by uesu** [comment]
> > Also is it possible or a feature suggestion to set the profile picture and name?
> 
> this is already possible if you go into the `channel settings` > `integrations` > `webhooks` there you can set a custom name & avatar

Yup I figured this just yesterday and tinkered with it, thanks once again!

As for embeds, I hope it's possible, if it's possible of course no pressure

**Comment by topi314** [comment]
> As for embeds, I hope it's possible, if it's possible of course no pressure

While it's possible I don't think that's something I want to implement here since that would require to fully proxy all Reddit videos

You can't simply embed a video in an embed, you have to proxy it over some webserver like the project you linked does which I have no interest in implementing tbh

What I could offer is a mode where it posts links to such a platform like rxddit.com which does already proxy videos

**Comment by topi314** [comment]
I added support for using reddit post proxies in https://github.com/topi314/Reddit-Discord-Bot/releases/tag/v2.0.0-beta.6

just specify format `link` & set the `proxy` option in the subscription

**Comment by uesu** [comment]
I see! thank you, I'll test and give it a try

**Comment by uesu** [comment]
> I added support for using reddit post proxies in https://github.com/topi314/Reddit-Discord-Bot/releases/tag/v2.0.0-beta.6
> 
> just specify format `link` & set the `proxy` option in the subscription

Alright feedback after months of testing, here's my suggestions for if it's possible to add or improve it, if it's possible of course no worries on this

- Instead of this, is it possible to have the format like this, so it's neat to look at
![Screenshot 2024-11-29 202455](https://github.com/user-attachments/assets/909e33bd-6932-4d5f-a44d-4a731030c251)
- So the message would be like "New post at (or from) r/(subreddit name)"
![Screenshot 2024-11-29 202210](https://github.com/user-attachments/assets/5f8eb005-9b7d-4954-8f84-26819b98f968)

Next is, possible to have 2 proxy links or more to use as a back-up (focused on video audio)

so it's like from the command (it has a comma perhaps like -> https://rxddit.com, https://vxreddit.com)

- since rxddit can have multiple embed images and almost all images can show it, but the only downside is the no audio on some long video and already explained on this: https://github.com/MinnDevelopment/fxreddit/issues/55#issuecomment-2124002034

If it's youtube, it just does this (this is on the proxy side, not the bot)

![Screenshot 2024-11-29 212229](https://github.com/user-attachments/assets/f439b83e-c2f9-4d47-816f-06091b4e579a)


- vxreddit can almost do video but takes a little bit of time to embed but it mostly works, but there are some cases, it does not
- another huge advantage of vxreddit is if it's a youtube link on reddit post, it would properly embed it through direct youtube, which i was surprised

![Screenshot 2024-11-29 212212](https://github.com/user-attachments/assets/f898698c-e4c7-406a-ad00-436955b77431)


- the downside is, it's formatting on embed (rxreddit does it better, but if on your bot topi reddit bot, the embed type is much the best tbh) and the multiple images on vxreddit is a no no as it does not support it

So like why and if it's possible to having or have 2 or more proxy links as a back-up

the scenario is like this, the bot would test it first if it's a video, then it prioritizes that it must have an audio so that would be the vxreddit proxy link, and if it's a success and it embeds properly, then the bot posts it, then if not -> it will look for the user's another proxy link provided -> so it's gonna be rxddit.com (but of course no audio, which is okay atleast the video embeds it properly) so it is like a fall-back

Though I don't know if this is possible on the bot

I'll show a video, it is on rxddit proxy by the bot but of course no audio (this is already understandable and it is on reddit api side)

Then my manual post using vxreddit for testing


https://github.com/user-attachments/assets/c9c7d343-122c-468d-95df-6cf419aef55c



Lastly if the video is too long and does not respond (vxreddit), it would fallback and use rxddit instead (no audio)

**Comment by topi314** [comment]
> So the message would be like "New post at (or from) r/(subreddit name)"

sure can do, no problem.

> Next is, possible to have 2 proxy links or more to use as a back-up (focused on video audio)

possible? probably, rn I only send the link to those sites an discord generates the embed on it's own from the html provided by these proxy sites.
So I can't really check if they "work" and fallback to a different one if it doesn't.

Now about prioritizing depending on if it's a video or not:
This kind of logic does seem kinda too much to me.
I'd rather have some "perfect" reddit proxy tbh, much simpler to fix it there if you ask me.
Detecting if a post is a video is also annoying.
Besides that I think it would also look weird using 2 different proxies since their embeds look different.

I saw the twitter thing you sent has those link buttons. Do you want those too? they are easy to add and could have some sort of setting attached

**Comment by uesu** [comment]
1. Yes, it appears to be neat, but you can also have the default one as a template (some users may prefer it only that default text method, and I don't want to anger other users who are using the bot)

2. I see, thank you for confirming or the explanation

3. True, that makes sense and is understandable

4. Oh, that's from the bot -> already native from it, but if you want to add that, you may, and other users who are using the bot may find it really beneficial

**Comment by topi314** [comment]
does this look good to you?
![image](https://github.com/user-attachments/assets/010a4e22-75e7-422f-adfa-46dd8fdf47cd)

I don't really want to start providing templates, just makes it more complicated and easier for people to fuck up tbh

**Comment by uesu** [comment]
10/10 yup, awesome

It's much more neat to be honest and does not repeat the title on embed

Ah what I meant is this, 
![391084531-909e33bd-6932-4d5f-a44d-4a731030c251](https://github.com/user-attachments/assets/d87d8317-0808-46e5-a6b0-2dead1c0a71e) 

There might be who knows if someone who uses the bot doesn't like it (but I doubt and you're safe because I'm assuming no discord support server right), but if someone will, then perhaps a user will create a github issue here, but once again, I doubt (though if there is, best to be prepared I guess)

> I don't really want to start providing templates, just makes it more complicated and easier for people to fuck up tbh

Ah I see, understandable for this, fair point

Then lastly, I see that you added buttons, is it adjustable for other users that like it (I have yet to try and see), such as some setting functionality or custom button functionality

**Comment by topi314** [comment]
the button is a simple on/off toggle I plan to enable for everyone by default, please keep in mind these changes are not yet live

**Comment by topi314** [comment]
There also is a discord support server linked at the bottom of the readme: https://github.com/topi314/Reddit-Discord-Bot#contact

**Comment by topi314** [comment]
changes should be live, you might need to restart your discord to see the new command arguments
