### ISSUE TITLE
Issue with images and links

### ISSUE THREAD

**Issue by ghost** [TopiSenpai/Reddit-Discord-Bot#11]
I am facing an issue with posts that contain multiple images attached. Such post media is not getting displayed on the channels.

Example: https://www.reddit.com/r/KeralaGW/s/fYys0BAJ7I

Another issue I am facing is RedGIFs links not getting embedded into channels.

Example: https://www.reddit.com/r/Cuckold/comments/1cbwxm7/theyre_nailing_us_so_hard_and_we_completely/

Feature suggestion: It would be great If we had an option to ignore the posts that contain specific flairs.

**Comment by topi314** [comment]
in https://github.com/topi314/Reddit-Discord-Bot/releases/tag/v2.0.0-beta.6 I added the option to use a reddit post proxy such as https://rxddit.com which can solve the issue of not embedding all images
