### ISSUE TITLE
Error when adding a subreddit

### ISSUE THREAD

**Issue by compumark** [TopiSenpai/Reddit-Discord-Bot#2]
When adding a subreddit with 
![image](https://user-images.githubusercontent.com/75847830/163475772-0bda3fa7-9df1-4776-a27c-8c392e5001ca.png)

this message appears: 
![image](https://user-images.githubusercontent.com/75847830/163475671-be28900e-c635-417d-a19e-f2659b761f90.png)

How to solve this? 
Thanks a lot,
Mark

**Comment by TopiSenpai** [comment]
is it possible that the channel already has 10 webhooks?

**Comment by compumark** [comment]
No, this channel has 0 webhooks, the whole server 5

**Comment by TopiSenpai** [comment]
no the bot should not be listed as it's not a real bot
just slash commands
I'll have a look ty for the report

**Comment by TopiSenpai** [comment]
I restarted it for now but it will prob stop responding at some point

**Comment by TopiSenpai** [comment]
if you notice it doesn't send any posts feel free to @ me here again. 
Hopefully I'll catch it myself

**Comment by compumark** [comment]
thanks a lot, I just created the webhook. I will monitor it.
