### ISSUE TITLE
Bot down

### ISSUE THREAD

**Issue by Cornstalk8567** [TopiSenpai/Reddit-Discord-Bot#4]
The bot's been down since 2147 EST May 2nd 2022. Any update on when it'll be back up again? Thanks.

**Comment by TopiSenpai** [comment]
should be up again

**Comment by Cornstalk8567** [comment]
Yup, working now. Thank you so much. Question - can I host this myself somewhere? I have a dedicated server (I run Debian on it), would it be possible to run it on that? If not possible, should I contact you if it goes down again? Are you on Discord? Sorry for so may questions, and thank you once again.

**Comment by TopiSenpai** [comment]
you could run it yourself but there is currently some bug which makes it go stuck every few days
I'm still in the process to try figure out where exactly that it is

so contacting me if it's down is prob your best bet atm

I'm currently doing a partial rewrite as I never thought I'd server around 200 subreddits and the cpu usage tells you the whole story

![image](https://user-images.githubusercontent.com/15636011/166657221-589be265-175a-41ba-aebd-dc3007dfb5f4.png)

https://github.com/TopiSenpai/Reddit-Discord-Bot/pull/3

**Comment by TopiSenpai** [comment]
feel free to join here to dm me or something if it's down then I can give it a quick restart

https://discord.gg/CGyPDNXy

**Comment by TopiSenpai** [comment]
idk if you are a programmer/know go but I'd be open for a pr if you can fix it
